name: skinscan
description: A mobile app for early skin cancer detection using AI
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  screenshot: ^3.0.0
  gal: ^2.3.2  # أو الإصدار الذي اقترحه لكِ البرنامج
  # UI & Icons
  cupertino_icons: ^1.0.8

  # Voice & Sound (For Welcome Screen)
  flutter_tts: ^4.2.2

  # Image Handling & Cropping
  image_picker: ^1.1.2
  image_cropper: ^8.0.2
  image: ^4.2.0

  # State Management
  provider: ^6.1.2

  # Storage & Path
  shared_preferences: ^2.3.2
  path_provider: ^2.1.5

  # Date/Time
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Asset folders configuration
  assets:
    - assets/images/
    - assets/model/